// Code generated by ent, DO NOT EDIT.

package sharedspacemember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldDeletedAt, v))
}

// SharedSpaceID applies equality check predicate on the "shared_space_id" field. It's identical to SharedSpaceIDEQ.
func SharedSpaceID(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldSharedSpaceID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldGroupID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotNull(FieldDeletedAt))
}

// SharedSpaceIDEQ applies the EQ predicate on the "shared_space_id" field.
func SharedSpaceIDEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldSharedSpaceID, v))
}

// SharedSpaceIDNEQ applies the NEQ predicate on the "shared_space_id" field.
func SharedSpaceIDNEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldSharedSpaceID, v))
}

// SharedSpaceIDIn applies the In predicate on the "shared_space_id" field.
func SharedSpaceIDIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldSharedSpaceID, vs...))
}

// SharedSpaceIDNotIn applies the NotIn predicate on the "shared_space_id" field.
func SharedSpaceIDNotIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldSharedSpaceID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotNull(FieldUserID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotNull(FieldGroupID))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.FieldNotIn(FieldRole, vs...))
}

// HasSharedSpace applies the HasEdge predicate on the "shared_space" edge.
func HasSharedSpace() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SharedSpaceTable, SharedSpaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSharedSpaceWith applies the HasEdge predicate on the "shared_space" edge with a given conditions (other predicates).
func HasSharedSpaceWith(preds ...predicate.SharedSpace) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := newSharedSpaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedSpaceMember) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedSpaceMember) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedSpaceMember) predicate.SharedSpaceMember {
	return predicate.SharedSpaceMember(sql.NotPredicates(p))
}
