// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpace is the model entity for the SharedSpace schema.
type SharedSpace struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// RootFileID holds the value of the "root_file_id" field.
	RootFileID int `json:"root_file_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SharedSpaceQuery when eager-loading is set.
	Edges        SharedSpaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SharedSpaceEdges holds the relations/edges for other nodes in the graph.
type SharedSpaceEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Members holds the value of the members edge.
	Members []*SharedSpaceMember `json:"members,omitempty"`
	// RootFile holds the value of the root_file edge.
	RootFile *File `json:"root_file,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharedSpaceEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e SharedSpaceEdges) MembersOrErr() ([]*SharedSpaceMember, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// RootFileOrErr returns the RootFile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharedSpaceEdges) RootFileOrErr() (*File, error) {
	if e.loadedTypes[2] {
		if e.RootFile == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: file.Label}
		}
		return e.RootFile, nil
	}
	return nil, &NotLoadedError{edge: "root_file"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedSpace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedspace.FieldID, sharedspace.FieldOwnerID, sharedspace.FieldRootFileID:
			values[i] = new(sql.NullInt64)
		case sharedspace.FieldName, sharedspace.FieldDescription:
			values[i] = new(sql.NullString)
		case sharedspace.FieldCreatedAt, sharedspace.FieldUpdatedAt, sharedspace.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedSpace fields.
func (ss *SharedSpace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedspace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ss.ID = int(value.Int64)
		case sharedspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ss.CreatedAt = value.Time
			}
		case sharedspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ss.UpdatedAt = value.Time
			}
		case sharedspace.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ss.DeletedAt = new(time.Time)
				*ss.DeletedAt = value.Time
			}
		case sharedspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ss.Name = value.String
			}
		case sharedspace.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ss.Description = value.String
			}
		case sharedspace.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				ss.OwnerID = int(value.Int64)
			}
		case sharedspace.FieldRootFileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field root_file_id", values[i])
			} else if value.Valid {
				ss.RootFileID = int(value.Int64)
			}
		default:
			ss.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedSpace.
// This includes values selected through modifiers, order, etc.
func (ss *SharedSpace) Value(name string) (ent.Value, error) {
	return ss.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the SharedSpace entity.
func (ss *SharedSpace) QueryOwner() *UserQuery {
	return NewSharedSpaceClient(ss.config).QueryOwner(ss)
}

// QueryMembers queries the "members" edge of the SharedSpace entity.
func (ss *SharedSpace) QueryMembers() *SharedSpaceMemberQuery {
	return NewSharedSpaceClient(ss.config).QueryMembers(ss)
}

// QueryRootFile queries the "root_file" edge of the SharedSpace entity.
func (ss *SharedSpace) QueryRootFile() *FileQuery {
	return NewSharedSpaceClient(ss.config).QueryRootFile(ss)
}

// Update returns a builder for updating this SharedSpace.
// Note that you need to call SharedSpace.Unwrap() before calling this method if this SharedSpace
// was returned from a transaction, and the transaction was committed or rolled back.
func (ss *SharedSpace) Update() *SharedSpaceUpdateOne {
	return NewSharedSpaceClient(ss.config).UpdateOne(ss)
}

// Unwrap unwraps the SharedSpace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ss *SharedSpace) Unwrap() *SharedSpace {
	_tx, ok := ss.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedSpace is not a transactional entity")
	}
	ss.config.driver = _tx.drv
	return ss
}

// String implements the fmt.Stringer.
func (ss *SharedSpace) String() string {
	var builder strings.Builder
	builder.WriteString("SharedSpace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ss.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ss.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ss.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ss.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ss.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ss.Description)
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", ss.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("root_file_id=")
	builder.WriteString(fmt.Sprintf("%v", ss.RootFileID))
	builder.WriteByte(')')
	return builder.String()
}

// SetOwner manually set the edge as loaded state.
func (e *SharedSpace) SetOwner(v *User) {
	e.Edges.Owner = v
	e.Edges.loadedTypes[0] = true
}

// SetMembers manually set the edge as loaded state.
func (e *SharedSpace) SetMembers(v []*SharedSpaceMember) {
	e.Edges.Members = v
	e.Edges.loadedTypes[1] = true
}

// SetRootFile manually set the edge as loaded state.
func (e *SharedSpace) SetRootFile(v *File) {
	e.Edges.RootFile = v
	e.Edges.loadedTypes[2] = true
}

// SharedSpaces is a parsable slice of SharedSpace.
type SharedSpaces []*SharedSpace
