// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceMemberCreate is the builder for creating a SharedSpaceMember entity.
type SharedSpaceMemberCreate struct {
	config
	mutation *SharedSpaceMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ssmc *SharedSpaceMemberCreate) SetCreatedAt(t time.Time) *SharedSpaceMemberCreate {
	ssmc.mutation.SetCreatedAt(t)
	return ssmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableCreatedAt(t *time.Time) *SharedSpaceMemberCreate {
	if t != nil {
		ssmc.SetCreatedAt(*t)
	}
	return ssmc
}

// SetUpdatedAt sets the "updated_at" field.
func (ssmc *SharedSpaceMemberCreate) SetUpdatedAt(t time.Time) *SharedSpaceMemberCreate {
	ssmc.mutation.SetUpdatedAt(t)
	return ssmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableUpdatedAt(t *time.Time) *SharedSpaceMemberCreate {
	if t != nil {
		ssmc.SetUpdatedAt(*t)
	}
	return ssmc
}

// SetDeletedAt sets the "deleted_at" field.
func (ssmc *SharedSpaceMemberCreate) SetDeletedAt(t time.Time) *SharedSpaceMemberCreate {
	ssmc.mutation.SetDeletedAt(t)
	return ssmc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableDeletedAt(t *time.Time) *SharedSpaceMemberCreate {
	if t != nil {
		ssmc.SetDeletedAt(*t)
	}
	return ssmc
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (ssmc *SharedSpaceMemberCreate) SetSharedSpaceID(i int) *SharedSpaceMemberCreate {
	ssmc.mutation.SetSharedSpaceID(i)
	return ssmc
}

// SetUserID sets the "user_id" field.
func (ssmc *SharedSpaceMemberCreate) SetUserID(i int) *SharedSpaceMemberCreate {
	ssmc.mutation.SetUserID(i)
	return ssmc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableUserID(i *int) *SharedSpaceMemberCreate {
	if i != nil {
		ssmc.SetUserID(*i)
	}
	return ssmc
}

// SetGroupID sets the "group_id" field.
func (ssmc *SharedSpaceMemberCreate) SetGroupID(i int) *SharedSpaceMemberCreate {
	ssmc.mutation.SetGroupID(i)
	return ssmc
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableGroupID(i *int) *SharedSpaceMemberCreate {
	if i != nil {
		ssmc.SetGroupID(*i)
	}
	return ssmc
}

// SetRole sets the "role" field.
func (ssmc *SharedSpaceMemberCreate) SetRole(s sharedspacemember.Role) *SharedSpaceMemberCreate {
	ssmc.mutation.SetRole(s)
	return ssmc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ssmc *SharedSpaceMemberCreate) SetNillableRole(s *sharedspacemember.Role) *SharedSpaceMemberCreate {
	if s != nil {
		ssmc.SetRole(*s)
	}
	return ssmc
}

// SetSharedSpace sets the "shared_space" edge to the SharedSpace entity.
func (ssmc *SharedSpaceMemberCreate) SetSharedSpace(s *SharedSpace) *SharedSpaceMemberCreate {
	return ssmc.SetSharedSpaceID(s.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ssmc *SharedSpaceMemberCreate) SetUser(u *User) *SharedSpaceMemberCreate {
	return ssmc.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (ssmc *SharedSpaceMemberCreate) SetGroup(g *Group) *SharedSpaceMemberCreate {
	return ssmc.SetGroupID(g.ID)
}

// Mutation returns the SharedSpaceMemberMutation object of the builder.
func (ssmc *SharedSpaceMemberCreate) Mutation() *SharedSpaceMemberMutation {
	return ssmc.mutation
}

// Save creates the SharedSpaceMember in the database.
func (ssmc *SharedSpaceMemberCreate) Save(ctx context.Context) (*SharedSpaceMember, error) {
	if err := ssmc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ssmc.sqlSave, ssmc.mutation, ssmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssmc *SharedSpaceMemberCreate) SaveX(ctx context.Context) *SharedSpaceMember {
	v, err := ssmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssmc *SharedSpaceMemberCreate) Exec(ctx context.Context) error {
	_, err := ssmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmc *SharedSpaceMemberCreate) ExecX(ctx context.Context) {
	if err := ssmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssmc *SharedSpaceMemberCreate) defaults() error {
	if _, ok := ssmc.mutation.CreatedAt(); !ok {
		if sharedspacemember.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspacemember.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspacemember.DefaultCreatedAt()
		ssmc.mutation.SetCreatedAt(v)
	}
	if _, ok := ssmc.mutation.UpdatedAt(); !ok {
		if sharedspacemember.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspacemember.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspacemember.DefaultUpdatedAt()
		ssmc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ssmc.mutation.Role(); !ok {
		v := sharedspacemember.DefaultRole
		ssmc.mutation.SetRole(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssmc *SharedSpaceMemberCreate) check() error {
	if _, ok := ssmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedSpaceMember.created_at"`)}
	}
	if _, ok := ssmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedSpaceMember.updated_at"`)}
	}
	if _, ok := ssmc.mutation.SharedSpaceID(); !ok {
		return &ValidationError{Name: "shared_space_id", err: errors.New(`ent: missing required field "SharedSpaceMember.shared_space_id"`)}
	}
	if _, ok := ssmc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "SharedSpaceMember.role"`)}
	}
	if v, ok := ssmc.mutation.Role(); ok {
		if err := sharedspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SharedSpaceMember.role": %w`, err)}
		}
	}
	if _, ok := ssmc.mutation.SharedSpaceID(); !ok {
		return &ValidationError{Name: "shared_space", err: errors.New(`ent: missing required edge "SharedSpaceMember.shared_space"`)}
	}
	return nil
}

func (ssmc *SharedSpaceMemberCreate) sqlSave(ctx context.Context) (*SharedSpaceMember, error) {
	if err := ssmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssmc.mutation.id = &_node.ID
	ssmc.mutation.done = true
	return _node, nil
}

func (ssmc *SharedSpaceMemberCreate) createSpec() (*SharedSpaceMember, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedSpaceMember{config: ssmc.config}
		_spec = sqlgraph.NewCreateSpec(sharedspacemember.Table, sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt))
	)

	if id, ok := ssmc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = ssmc.conflict
	if value, ok := ssmc.mutation.CreatedAt(); ok {
		_spec.SetField(sharedspacemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ssmc.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspacemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ssmc.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspacemember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ssmc.mutation.Role(); ok {
		_spec.SetField(sharedspacemember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := ssmc.mutation.SharedSpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.SharedSpaceTable,
			Columns: []string{sharedspacemember.SharedSpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SharedSpaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ssmc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.UserTable,
			Columns: []string{sharedspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ssmc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.GroupTable,
			Columns: []string{sharedspacemember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedSpaceMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedSpaceMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ssmc *SharedSpaceMemberCreate) OnConflict(opts ...sql.ConflictOption) *SharedSpaceMemberUpsertOne {
	ssmc.conflict = opts
	return &SharedSpaceMemberUpsertOne{
		create: ssmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ssmc *SharedSpaceMemberCreate) OnConflictColumns(columns ...string) *SharedSpaceMemberUpsertOne {
	ssmc.conflict = append(ssmc.conflict, sql.ConflictColumns(columns...))
	return &SharedSpaceMemberUpsertOne{
		create: ssmc,
	}
}

type (
	// SharedSpaceMemberUpsertOne is the builder for "upsert"-ing
	//  one SharedSpaceMember node.
	SharedSpaceMemberUpsertOne struct {
		create *SharedSpaceMemberCreate
	}

	// SharedSpaceMemberUpsert is the "OnConflict" setter.
	SharedSpaceMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceMemberUpsert) SetUpdatedAt(v time.Time) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateUpdatedAt() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceMemberUpsert) SetDeletedAt(v time.Time) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateDeletedAt() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceMemberUpsert) ClearDeletedAt() *SharedSpaceMemberUpsert {
	u.SetNull(sharedspacemember.FieldDeletedAt)
	return u
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (u *SharedSpaceMemberUpsert) SetSharedSpaceID(v int) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldSharedSpaceID, v)
	return u
}

// UpdateSharedSpaceID sets the "shared_space_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateSharedSpaceID() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldSharedSpaceID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SharedSpaceMemberUpsert) SetUserID(v int) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateUserID() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *SharedSpaceMemberUpsert) ClearUserID() *SharedSpaceMemberUpsert {
	u.SetNull(sharedspacemember.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SharedSpaceMemberUpsert) SetGroupID(v int) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateGroupID() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SharedSpaceMemberUpsert) ClearGroupID() *SharedSpaceMemberUpsert {
	u.SetNull(sharedspacemember.FieldGroupID)
	return u
}

// SetRole sets the "role" field.
func (u *SharedSpaceMemberUpsert) SetRole(v sharedspacemember.Role) *SharedSpaceMemberUpsert {
	u.Set(sharedspacemember.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsert) UpdateRole() *SharedSpaceMemberUpsert {
	u.SetExcluded(sharedspacemember.FieldRole)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedSpaceMemberUpsertOne) UpdateNewValues() *SharedSpaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharedspacemember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedSpaceMemberUpsertOne) Ignore() *SharedSpaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedSpaceMemberUpsertOne) DoNothing() *SharedSpaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedSpaceMemberCreate.OnConflict
// documentation for more info.
func (u *SharedSpaceMemberUpsertOne) Update(set func(*SharedSpaceMemberUpsert)) *SharedSpaceMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedSpaceMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceMemberUpsertOne) SetUpdatedAt(v time.Time) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateUpdatedAt() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceMemberUpsertOne) SetDeletedAt(v time.Time) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateDeletedAt() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceMemberUpsertOne) ClearDeletedAt() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (u *SharedSpaceMemberUpsertOne) SetSharedSpaceID(v int) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetSharedSpaceID(v)
	})
}

// UpdateSharedSpaceID sets the "shared_space_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateSharedSpaceID() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateSharedSpaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SharedSpaceMemberUpsertOne) SetUserID(v int) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateUserID() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SharedSpaceMemberUpsertOne) ClearUserID() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SharedSpaceMemberUpsertOne) SetGroupID(v int) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateGroupID() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SharedSpaceMemberUpsertOne) ClearGroupID() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearGroupID()
	})
}

// SetRole sets the "role" field.
func (u *SharedSpaceMemberUpsertOne) SetRole(v sharedspacemember.Role) *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertOne) UpdateRole() *SharedSpaceMemberUpsertOne {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *SharedSpaceMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedSpaceMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedSpaceMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedSpaceMemberUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedSpaceMemberUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *SharedSpaceMemberCreate) SetRawID(t int) *SharedSpaceMemberCreate {
	m.mutation.SetRawID(t)
	return m
}

// SharedSpaceMemberCreateBulk is the builder for creating many SharedSpaceMember entities in bulk.
type SharedSpaceMemberCreateBulk struct {
	config
	err      error
	builders []*SharedSpaceMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedSpaceMember entities in the database.
func (ssmcb *SharedSpaceMemberCreateBulk) Save(ctx context.Context) ([]*SharedSpaceMember, error) {
	if ssmcb.err != nil {
		return nil, ssmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ssmcb.builders))
	nodes := make([]*SharedSpaceMember, len(ssmcb.builders))
	mutators := make([]Mutator, len(ssmcb.builders))
	for i := range ssmcb.builders {
		func(i int, root context.Context) {
			builder := ssmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedSpaceMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ssmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ssmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ssmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ssmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ssmcb *SharedSpaceMemberCreateBulk) SaveX(ctx context.Context) []*SharedSpaceMember {
	v, err := ssmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssmcb *SharedSpaceMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := ssmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmcb *SharedSpaceMemberCreateBulk) ExecX(ctx context.Context) {
	if err := ssmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedSpaceMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedSpaceMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ssmcb *SharedSpaceMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedSpaceMemberUpsertBulk {
	ssmcb.conflict = opts
	return &SharedSpaceMemberUpsertBulk{
		create: ssmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ssmcb *SharedSpaceMemberCreateBulk) OnConflictColumns(columns ...string) *SharedSpaceMemberUpsertBulk {
	ssmcb.conflict = append(ssmcb.conflict, sql.ConflictColumns(columns...))
	return &SharedSpaceMemberUpsertBulk{
		create: ssmcb,
	}
}

// SharedSpaceMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedSpaceMember nodes.
type SharedSpaceMemberUpsertBulk struct {
	create *SharedSpaceMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedSpaceMemberUpsertBulk) UpdateNewValues() *SharedSpaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharedspacemember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedSpaceMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedSpaceMemberUpsertBulk) Ignore() *SharedSpaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedSpaceMemberUpsertBulk) DoNothing() *SharedSpaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedSpaceMemberCreateBulk.OnConflict
// documentation for more info.
func (u *SharedSpaceMemberUpsertBulk) Update(set func(*SharedSpaceMemberUpsert)) *SharedSpaceMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedSpaceMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceMemberUpsertBulk) SetUpdatedAt(v time.Time) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateUpdatedAt() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceMemberUpsertBulk) SetDeletedAt(v time.Time) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateDeletedAt() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceMemberUpsertBulk) ClearDeletedAt() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (u *SharedSpaceMemberUpsertBulk) SetSharedSpaceID(v int) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetSharedSpaceID(v)
	})
}

// UpdateSharedSpaceID sets the "shared_space_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateSharedSpaceID() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateSharedSpaceID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SharedSpaceMemberUpsertBulk) SetUserID(v int) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateUserID() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SharedSpaceMemberUpsertBulk) ClearUserID() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SharedSpaceMemberUpsertBulk) SetGroupID(v int) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateGroupID() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SharedSpaceMemberUpsertBulk) ClearGroupID() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.ClearGroupID()
	})
}

// SetRole sets the "role" field.
func (u *SharedSpaceMemberUpsertBulk) SetRole(v sharedspacemember.Role) *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SharedSpaceMemberUpsertBulk) UpdateRole() *SharedSpaceMemberUpsertBulk {
	return u.Update(func(s *SharedSpaceMemberUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *SharedSpaceMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedSpaceMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedSpaceMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedSpaceMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
