// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceMember is the model entity for the SharedSpaceMember schema.
type SharedSpaceMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// SharedSpaceID holds the value of the "shared_space_id" field.
	SharedSpaceID int `json:"shared_space_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int `json:"group_id,omitempty"`
	// Role holds the value of the "role" field.
	Role sharedspacemember.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SharedSpaceMemberQuery when eager-loading is set.
	Edges        SharedSpaceMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SharedSpaceMemberEdges holds the relations/edges for other nodes in the graph.
type SharedSpaceMemberEdges struct {
	// SharedSpace holds the value of the shared_space edge.
	SharedSpace *SharedSpace `json:"shared_space,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SharedSpaceOrErr returns the SharedSpace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharedSpaceMemberEdges) SharedSpaceOrErr() (*SharedSpace, error) {
	if e.loadedTypes[0] {
		if e.SharedSpace == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sharedspace.Label}
		}
		return e.SharedSpace, nil
	}
	return nil, &NotLoadedError{edge: "shared_space"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharedSpaceMemberEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharedSpaceMemberEdges) GroupOrErr() (*Group, error) {
	if e.loadedTypes[2] {
		if e.Group == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: group.Label}
		}
		return e.Group, nil
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedSpaceMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedspacemember.FieldID, sharedspacemember.FieldSharedSpaceID, sharedspacemember.FieldUserID, sharedspacemember.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case sharedspacemember.FieldRole:
			values[i] = new(sql.NullString)
		case sharedspacemember.FieldCreatedAt, sharedspacemember.FieldUpdatedAt, sharedspacemember.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedSpaceMember fields.
func (ssm *SharedSpaceMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedspacemember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ssm.ID = int(value.Int64)
		case sharedspacemember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ssm.CreatedAt = value.Time
			}
		case sharedspacemember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ssm.UpdatedAt = value.Time
			}
		case sharedspacemember.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ssm.DeletedAt = new(time.Time)
				*ssm.DeletedAt = value.Time
			}
		case sharedspacemember.FieldSharedSpaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shared_space_id", values[i])
			} else if value.Valid {
				ssm.SharedSpaceID = int(value.Int64)
			}
		case sharedspacemember.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ssm.UserID = int(value.Int64)
			}
		case sharedspacemember.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				ssm.GroupID = int(value.Int64)
			}
		case sharedspacemember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				ssm.Role = sharedspacemember.Role(value.String)
			}
		default:
			ssm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedSpaceMember.
// This includes values selected through modifiers, order, etc.
func (ssm *SharedSpaceMember) Value(name string) (ent.Value, error) {
	return ssm.selectValues.Get(name)
}

// QuerySharedSpace queries the "shared_space" edge of the SharedSpaceMember entity.
func (ssm *SharedSpaceMember) QuerySharedSpace() *SharedSpaceQuery {
	return NewSharedSpaceMemberClient(ssm.config).QuerySharedSpace(ssm)
}

// QueryUser queries the "user" edge of the SharedSpaceMember entity.
func (ssm *SharedSpaceMember) QueryUser() *UserQuery {
	return NewSharedSpaceMemberClient(ssm.config).QueryUser(ssm)
}

// QueryGroup queries the "group" edge of the SharedSpaceMember entity.
func (ssm *SharedSpaceMember) QueryGroup() *GroupQuery {
	return NewSharedSpaceMemberClient(ssm.config).QueryGroup(ssm)
}

// Update returns a builder for updating this SharedSpaceMember.
// Note that you need to call SharedSpaceMember.Unwrap() before calling this method if this SharedSpaceMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (ssm *SharedSpaceMember) Update() *SharedSpaceMemberUpdateOne {
	return NewSharedSpaceMemberClient(ssm.config).UpdateOne(ssm)
}

// Unwrap unwraps the SharedSpaceMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ssm *SharedSpaceMember) Unwrap() *SharedSpaceMember {
	_tx, ok := ssm.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedSpaceMember is not a transactional entity")
	}
	ssm.config.driver = _tx.drv
	return ssm
}

// String implements the fmt.Stringer.
func (ssm *SharedSpaceMember) String() string {
	var builder strings.Builder
	builder.WriteString("SharedSpaceMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ssm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ssm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ssm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ssm.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("shared_space_id=")
	builder.WriteString(fmt.Sprintf("%v", ssm.SharedSpaceID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ssm.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", ssm.GroupID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", ssm.Role))
	builder.WriteByte(')')
	return builder.String()
}

// SetSharedSpace manually set the edge as loaded state.
func (e *SharedSpaceMember) SetSharedSpace(v *SharedSpace) {
	e.Edges.SharedSpace = v
	e.Edges.loadedTypes[0] = true
}

// SetUser manually set the edge as loaded state.
func (e *SharedSpaceMember) SetUser(v *User) {
	e.Edges.User = v
	e.Edges.loadedTypes[1] = true
}

// SetGroup manually set the edge as loaded state.
func (e *SharedSpaceMember) SetGroup(v *Group) {
	e.Edges.Group = v
	e.Edges.loadedTypes[2] = true
}

// SharedSpaceMembers is a parsable slice of SharedSpaceMember.
type SharedSpaceMembers []*SharedSpaceMember
