// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceCreate is the builder for creating a SharedSpace entity.
type SharedSpaceCreate struct {
	config
	mutation *SharedSpaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ssc *SharedSpaceCreate) SetCreatedAt(t time.Time) *SharedSpaceCreate {
	ssc.mutation.SetCreatedAt(t)
	return ssc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ssc *SharedSpaceCreate) SetNillableCreatedAt(t *time.Time) *SharedSpaceCreate {
	if t != nil {
		ssc.SetCreatedAt(*t)
	}
	return ssc
}

// SetUpdatedAt sets the "updated_at" field.
func (ssc *SharedSpaceCreate) SetUpdatedAt(t time.Time) *SharedSpaceCreate {
	ssc.mutation.SetUpdatedAt(t)
	return ssc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ssc *SharedSpaceCreate) SetNillableUpdatedAt(t *time.Time) *SharedSpaceCreate {
	if t != nil {
		ssc.SetUpdatedAt(*t)
	}
	return ssc
}

// SetDeletedAt sets the "deleted_at" field.
func (ssc *SharedSpaceCreate) SetDeletedAt(t time.Time) *SharedSpaceCreate {
	ssc.mutation.SetDeletedAt(t)
	return ssc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssc *SharedSpaceCreate) SetNillableDeletedAt(t *time.Time) *SharedSpaceCreate {
	if t != nil {
		ssc.SetDeletedAt(*t)
	}
	return ssc
}

// SetName sets the "name" field.
func (ssc *SharedSpaceCreate) SetName(s string) *SharedSpaceCreate {
	ssc.mutation.SetName(s)
	return ssc
}

// SetDescription sets the "description" field.
func (ssc *SharedSpaceCreate) SetDescription(s string) *SharedSpaceCreate {
	ssc.mutation.SetDescription(s)
	return ssc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ssc *SharedSpaceCreate) SetNillableDescription(s *string) *SharedSpaceCreate {
	if s != nil {
		ssc.SetDescription(*s)
	}
	return ssc
}

// SetOwnerID sets the "owner_id" field.
func (ssc *SharedSpaceCreate) SetOwnerID(i int) *SharedSpaceCreate {
	ssc.mutation.SetOwnerID(i)
	return ssc
}

// SetRootFileID sets the "root_file_id" field.
func (ssc *SharedSpaceCreate) SetRootFileID(i int) *SharedSpaceCreate {
	ssc.mutation.SetRootFileID(i)
	return ssc
}

// SetNillableRootFileID sets the "root_file_id" field if the given value is not nil.
func (ssc *SharedSpaceCreate) SetNillableRootFileID(i *int) *SharedSpaceCreate {
	if i != nil {
		ssc.SetRootFileID(*i)
	}
	return ssc
}

// SetOwner sets the "owner" edge to the User entity.
func (ssc *SharedSpaceCreate) SetOwner(u *User) *SharedSpaceCreate {
	return ssc.SetOwnerID(u.ID)
}

// AddMemberIDs adds the "members" edge to the SharedSpaceMember entity by IDs.
func (ssc *SharedSpaceCreate) AddMemberIDs(ids ...int) *SharedSpaceCreate {
	ssc.mutation.AddMemberIDs(ids...)
	return ssc
}

// AddMembers adds the "members" edges to the SharedSpaceMember entity.
func (ssc *SharedSpaceCreate) AddMembers(s ...*SharedSpaceMember) *SharedSpaceCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ssc.AddMemberIDs(ids...)
}

// SetRootFile sets the "root_file" edge to the File entity.
func (ssc *SharedSpaceCreate) SetRootFile(f *File) *SharedSpaceCreate {
	return ssc.SetRootFileID(f.ID)
}

// Mutation returns the SharedSpaceMutation object of the builder.
func (ssc *SharedSpaceCreate) Mutation() *SharedSpaceMutation {
	return ssc.mutation
}

// Save creates the SharedSpace in the database.
func (ssc *SharedSpaceCreate) Save(ctx context.Context) (*SharedSpace, error) {
	if err := ssc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ssc.sqlSave, ssc.mutation, ssc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssc *SharedSpaceCreate) SaveX(ctx context.Context) *SharedSpace {
	v, err := ssc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssc *SharedSpaceCreate) Exec(ctx context.Context) error {
	_, err := ssc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssc *SharedSpaceCreate) ExecX(ctx context.Context) {
	if err := ssc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssc *SharedSpaceCreate) defaults() error {
	if _, ok := ssc.mutation.CreatedAt(); !ok {
		if sharedspace.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspace.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspace.DefaultCreatedAt()
		ssc.mutation.SetCreatedAt(v)
	}
	if _, ok := ssc.mutation.UpdatedAt(); !ok {
		if sharedspace.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspace.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspace.DefaultUpdatedAt()
		ssc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssc *SharedSpaceCreate) check() error {
	if _, ok := ssc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SharedSpace.created_at"`)}
	}
	if _, ok := ssc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SharedSpace.updated_at"`)}
	}
	if _, ok := ssc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SharedSpace.name"`)}
	}
	if v, ok := ssc.mutation.Name(); ok {
		if err := sharedspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.name": %w`, err)}
		}
	}
	if v, ok := ssc.mutation.Description(); ok {
		if err := sharedspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.description": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "SharedSpace.owner_id"`)}
	}
	if _, ok := ssc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "SharedSpace.owner"`)}
	}
	return nil
}

func (ssc *SharedSpaceCreate) sqlSave(ctx context.Context) (*SharedSpace, error) {
	if err := ssc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssc.mutation.id = &_node.ID
	ssc.mutation.done = true
	return _node, nil
}

func (ssc *SharedSpaceCreate) createSpec() (*SharedSpace, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedSpace{config: ssc.config}
		_spec = sqlgraph.NewCreateSpec(sharedspace.Table, sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt))
	)

	if id, ok := ssc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = ssc.conflict
	if value, ok := ssc.mutation.CreatedAt(); ok {
		_spec.SetField(sharedspace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ssc.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspace.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ssc.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspace.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ssc.mutation.Name(); ok {
		_spec.SetField(sharedspace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ssc.mutation.Description(); ok {
		_spec.SetField(sharedspace.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := ssc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspace.OwnerTable,
			Columns: []string{sharedspace.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ssc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ssc.mutation.RootFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sharedspace.RootFileTable,
			Columns: []string{sharedspace.RootFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RootFileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedSpace.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedSpaceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ssc *SharedSpaceCreate) OnConflict(opts ...sql.ConflictOption) *SharedSpaceUpsertOne {
	ssc.conflict = opts
	return &SharedSpaceUpsertOne{
		create: ssc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ssc *SharedSpaceCreate) OnConflictColumns(columns ...string) *SharedSpaceUpsertOne {
	ssc.conflict = append(ssc.conflict, sql.ConflictColumns(columns...))
	return &SharedSpaceUpsertOne{
		create: ssc,
	}
}

type (
	// SharedSpaceUpsertOne is the builder for "upsert"-ing
	//  one SharedSpace node.
	SharedSpaceUpsertOne struct {
		create *SharedSpaceCreate
	}

	// SharedSpaceUpsert is the "OnConflict" setter.
	SharedSpaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceUpsert) SetUpdatedAt(v time.Time) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateUpdatedAt() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceUpsert) SetDeletedAt(v time.Time) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateDeletedAt() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceUpsert) ClearDeletedAt() *SharedSpaceUpsert {
	u.SetNull(sharedspace.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *SharedSpaceUpsert) SetName(v string) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateName() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SharedSpaceUpsert) SetDescription(v string) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateDescription() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SharedSpaceUpsert) ClearDescription() *SharedSpaceUpsert {
	u.SetNull(sharedspace.FieldDescription)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *SharedSpaceUpsert) SetOwnerID(v int) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateOwnerID() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldOwnerID)
	return u
}

// SetRootFileID sets the "root_file_id" field.
func (u *SharedSpaceUpsert) SetRootFileID(v int) *SharedSpaceUpsert {
	u.Set(sharedspace.FieldRootFileID, v)
	return u
}

// UpdateRootFileID sets the "root_file_id" field to the value that was provided on create.
func (u *SharedSpaceUpsert) UpdateRootFileID() *SharedSpaceUpsert {
	u.SetExcluded(sharedspace.FieldRootFileID)
	return u
}

// ClearRootFileID clears the value of the "root_file_id" field.
func (u *SharedSpaceUpsert) ClearRootFileID() *SharedSpaceUpsert {
	u.SetNull(sharedspace.FieldRootFileID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedSpaceUpsertOne) UpdateNewValues() *SharedSpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sharedspace.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedSpaceUpsertOne) Ignore() *SharedSpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedSpaceUpsertOne) DoNothing() *SharedSpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedSpaceCreate.OnConflict
// documentation for more info.
func (u *SharedSpaceUpsertOne) Update(set func(*SharedSpaceUpsert)) *SharedSpaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedSpaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceUpsertOne) SetUpdatedAt(v time.Time) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateUpdatedAt() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceUpsertOne) SetDeletedAt(v time.Time) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateDeletedAt() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceUpsertOne) ClearDeletedAt() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SharedSpaceUpsertOne) SetName(v string) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateName() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SharedSpaceUpsertOne) SetDescription(v string) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateDescription() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SharedSpaceUpsertOne) ClearDescription() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearDescription()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *SharedSpaceUpsertOne) SetOwnerID(v int) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateOwnerID() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateOwnerID()
	})
}

// SetRootFileID sets the "root_file_id" field.
func (u *SharedSpaceUpsertOne) SetRootFileID(v int) *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetRootFileID(v)
	})
}

// UpdateRootFileID sets the "root_file_id" field to the value that was provided on create.
func (u *SharedSpaceUpsertOne) UpdateRootFileID() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateRootFileID()
	})
}

// ClearRootFileID clears the value of the "root_file_id" field.
func (u *SharedSpaceUpsertOne) ClearRootFileID() *SharedSpaceUpsertOne {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearRootFileID()
	})
}

// Exec executes the query.
func (u *SharedSpaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedSpaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedSpaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedSpaceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedSpaceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *SharedSpaceCreate) SetRawID(t int) *SharedSpaceCreate {
	m.mutation.SetRawID(t)
	return m
}

// SharedSpaceCreateBulk is the builder for creating many SharedSpace entities in bulk.
type SharedSpaceCreateBulk struct {
	config
	err      error
	builders []*SharedSpaceCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedSpace entities in the database.
func (sscb *SharedSpaceCreateBulk) Save(ctx context.Context) ([]*SharedSpace, error) {
	if sscb.err != nil {
		return nil, sscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sscb.builders))
	nodes := make([]*SharedSpace, len(sscb.builders))
	mutators := make([]Mutator, len(sscb.builders))
	for i := range sscb.builders {
		func(i int, root context.Context) {
			builder := sscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedSpaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sscb *SharedSpaceCreateBulk) SaveX(ctx context.Context) []*SharedSpace {
	v, err := sscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sscb *SharedSpaceCreateBulk) Exec(ctx context.Context) error {
	_, err := sscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscb *SharedSpaceCreateBulk) ExecX(ctx context.Context) {
	if err := sscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedSpace.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedSpaceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sscb *SharedSpaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedSpaceUpsertBulk {
	sscb.conflict = opts
	return &SharedSpaceUpsertBulk{
		create: sscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sscb *SharedSpaceCreateBulk) OnConflictColumns(columns ...string) *SharedSpaceUpsertBulk {
	sscb.conflict = append(sscb.conflict, sql.ConflictColumns(columns...))
	return &SharedSpaceUpsertBulk{
		create: sscb,
	}
}

// SharedSpaceUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedSpace nodes.
type SharedSpaceUpsertBulk struct {
	create *SharedSpaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SharedSpaceUpsertBulk) UpdateNewValues() *SharedSpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sharedspace.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedSpace.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedSpaceUpsertBulk) Ignore() *SharedSpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedSpaceUpsertBulk) DoNothing() *SharedSpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedSpaceCreateBulk.OnConflict
// documentation for more info.
func (u *SharedSpaceUpsertBulk) Update(set func(*SharedSpaceUpsert)) *SharedSpaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedSpaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SharedSpaceUpsertBulk) SetUpdatedAt(v time.Time) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateUpdatedAt() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SharedSpaceUpsertBulk) SetDeletedAt(v time.Time) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateDeletedAt() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SharedSpaceUpsertBulk) ClearDeletedAt() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SharedSpaceUpsertBulk) SetName(v string) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateName() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SharedSpaceUpsertBulk) SetDescription(v string) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateDescription() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SharedSpaceUpsertBulk) ClearDescription() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearDescription()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *SharedSpaceUpsertBulk) SetOwnerID(v int) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateOwnerID() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateOwnerID()
	})
}

// SetRootFileID sets the "root_file_id" field.
func (u *SharedSpaceUpsertBulk) SetRootFileID(v int) *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.SetRootFileID(v)
	})
}

// UpdateRootFileID sets the "root_file_id" field to the value that was provided on create.
func (u *SharedSpaceUpsertBulk) UpdateRootFileID() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.UpdateRootFileID()
	})
}

// ClearRootFileID clears the value of the "root_file_id" field.
func (u *SharedSpaceUpsertBulk) ClearRootFileID() *SharedSpaceUpsertBulk {
	return u.Update(func(s *SharedSpaceUpsert) {
		s.ClearRootFileID()
	})
}

// Exec executes the query.
func (u *SharedSpaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedSpaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedSpaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedSpaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
