// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceMemberQuery is the builder for querying SharedSpaceMember entities.
type SharedSpaceMemberQuery struct {
	config
	ctx             *QueryContext
	order           []sharedspacemember.OrderOption
	inters          []Interceptor
	predicates      []predicate.SharedSpaceMember
	withSharedSpace *SharedSpaceQuery
	withUser        *UserQuery
	withGroup       *GroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SharedSpaceMemberQuery builder.
func (ssmq *SharedSpaceMemberQuery) Where(ps ...predicate.SharedSpaceMember) *SharedSpaceMemberQuery {
	ssmq.predicates = append(ssmq.predicates, ps...)
	return ssmq
}

// Limit the number of records to be returned by this query.
func (ssmq *SharedSpaceMemberQuery) Limit(limit int) *SharedSpaceMemberQuery {
	ssmq.ctx.Limit = &limit
	return ssmq
}

// Offset to start from.
func (ssmq *SharedSpaceMemberQuery) Offset(offset int) *SharedSpaceMemberQuery {
	ssmq.ctx.Offset = &offset
	return ssmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssmq *SharedSpaceMemberQuery) Unique(unique bool) *SharedSpaceMemberQuery {
	ssmq.ctx.Unique = &unique
	return ssmq
}

// Order specifies how the records should be ordered.
func (ssmq *SharedSpaceMemberQuery) Order(o ...sharedspacemember.OrderOption) *SharedSpaceMemberQuery {
	ssmq.order = append(ssmq.order, o...)
	return ssmq
}

// QuerySharedSpace chains the current query on the "shared_space" edge.
func (ssmq *SharedSpaceMemberQuery) QuerySharedSpace() *SharedSpaceQuery {
	query := (&SharedSpaceClient{config: ssmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspacemember.Table, sharedspacemember.FieldID, selector),
			sqlgraph.To(sharedspace.Table, sharedspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedspacemember.SharedSpaceTable, sharedspacemember.SharedSpaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (ssmq *SharedSpaceMemberQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ssmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspacemember.Table, sharedspacemember.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedspacemember.UserTable, sharedspacemember.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (ssmq *SharedSpaceMemberQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: ssmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspacemember.Table, sharedspacemember.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedspacemember.GroupTable, sharedspacemember.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SharedSpaceMember entity from the query.
// Returns a *NotFoundError when no SharedSpaceMember was found.
func (ssmq *SharedSpaceMemberQuery) First(ctx context.Context) (*SharedSpaceMember, error) {
	nodes, err := ssmq.Limit(1).All(setContextOp(ctx, ssmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharedspacemember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) FirstX(ctx context.Context) *SharedSpaceMember {
	node, err := ssmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SharedSpaceMember ID from the query.
// Returns a *NotFoundError when no SharedSpaceMember ID was found.
func (ssmq *SharedSpaceMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssmq.Limit(1).IDs(setContextOp(ctx, ssmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharedspacemember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := ssmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SharedSpaceMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SharedSpaceMember entity is found.
// Returns a *NotFoundError when no SharedSpaceMember entities are found.
func (ssmq *SharedSpaceMemberQuery) Only(ctx context.Context) (*SharedSpaceMember, error) {
	nodes, err := ssmq.Limit(2).All(setContextOp(ctx, ssmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharedspacemember.Label}
	default:
		return nil, &NotSingularError{sharedspacemember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) OnlyX(ctx context.Context) *SharedSpaceMember {
	node, err := ssmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SharedSpaceMember ID in the query.
// Returns a *NotSingularError when more than one SharedSpaceMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssmq *SharedSpaceMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssmq.Limit(2).IDs(setContextOp(ctx, ssmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharedspacemember.Label}
	default:
		err = &NotSingularError{sharedspacemember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SharedSpaceMembers.
func (ssmq *SharedSpaceMemberQuery) All(ctx context.Context) ([]*SharedSpaceMember, error) {
	ctx = setContextOp(ctx, ssmq.ctx, "All")
	if err := ssmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SharedSpaceMember, *SharedSpaceMemberQuery]()
	return withInterceptors[[]*SharedSpaceMember](ctx, ssmq, qr, ssmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) AllX(ctx context.Context) []*SharedSpaceMember {
	nodes, err := ssmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SharedSpaceMember IDs.
func (ssmq *SharedSpaceMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssmq.ctx.Unique == nil && ssmq.path != nil {
		ssmq.Unique(true)
	}
	ctx = setContextOp(ctx, ssmq.ctx, "IDs")
	if err = ssmq.Select(sharedspacemember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := ssmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssmq *SharedSpaceMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssmq.ctx, "Count")
	if err := ssmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssmq, querierCount[*SharedSpaceMemberQuery](), ssmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) CountX(ctx context.Context) int {
	count, err := ssmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssmq *SharedSpaceMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssmq.ctx, "Exist")
	switch _, err := ssmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssmq *SharedSpaceMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := ssmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SharedSpaceMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssmq *SharedSpaceMemberQuery) Clone() *SharedSpaceMemberQuery {
	if ssmq == nil {
		return nil
	}
	return &SharedSpaceMemberQuery{
		config:          ssmq.config,
		ctx:             ssmq.ctx.Clone(),
		order:           append([]sharedspacemember.OrderOption{}, ssmq.order...),
		inters:          append([]Interceptor{}, ssmq.inters...),
		predicates:      append([]predicate.SharedSpaceMember{}, ssmq.predicates...),
		withSharedSpace: ssmq.withSharedSpace.Clone(),
		withUser:        ssmq.withUser.Clone(),
		withGroup:       ssmq.withGroup.Clone(),
		// clone intermediate query.
		sql:  ssmq.sql.Clone(),
		path: ssmq.path,
	}
}

// WithSharedSpace tells the query-builder to eager-load the nodes that are connected to
// the "shared_space" edge. The optional arguments are used to configure the query builder of the edge.
func (ssmq *SharedSpaceMemberQuery) WithSharedSpace(opts ...func(*SharedSpaceQuery)) *SharedSpaceMemberQuery {
	query := (&SharedSpaceClient{config: ssmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssmq.withSharedSpace = query
	return ssmq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ssmq *SharedSpaceMemberQuery) WithUser(opts ...func(*UserQuery)) *SharedSpaceMemberQuery {
	query := (&UserClient{config: ssmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssmq.withUser = query
	return ssmq
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (ssmq *SharedSpaceMemberQuery) WithGroup(opts ...func(*GroupQuery)) *SharedSpaceMemberQuery {
	query := (&GroupClient{config: ssmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssmq.withGroup = query
	return ssmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SharedSpaceMember.Query().
//		GroupBy(sharedspacemember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssmq *SharedSpaceMemberQuery) GroupBy(field string, fields ...string) *SharedSpaceMemberGroupBy {
	ssmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SharedSpaceMemberGroupBy{build: ssmq}
	grbuild.flds = &ssmq.ctx.Fields
	grbuild.label = sharedspacemember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SharedSpaceMember.Query().
//		Select(sharedspacemember.FieldCreatedAt).
//		Scan(ctx, &v)
func (ssmq *SharedSpaceMemberQuery) Select(fields ...string) *SharedSpaceMemberSelect {
	ssmq.ctx.Fields = append(ssmq.ctx.Fields, fields...)
	sbuild := &SharedSpaceMemberSelect{SharedSpaceMemberQuery: ssmq}
	sbuild.label = sharedspacemember.Label
	sbuild.flds, sbuild.scan = &ssmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SharedSpaceMemberSelect configured with the given aggregations.
func (ssmq *SharedSpaceMemberQuery) Aggregate(fns ...AggregateFunc) *SharedSpaceMemberSelect {
	return ssmq.Select().Aggregate(fns...)
}

func (ssmq *SharedSpaceMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssmq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssmq.ctx.Fields {
		if !sharedspacemember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssmq.path != nil {
		prev, err := ssmq.path(ctx)
		if err != nil {
			return err
		}
		ssmq.sql = prev
	}
	return nil
}

func (ssmq *SharedSpaceMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SharedSpaceMember, error) {
	var (
		nodes       = []*SharedSpaceMember{}
		_spec       = ssmq.querySpec()
		loadedTypes = [3]bool{
			ssmq.withSharedSpace != nil,
			ssmq.withUser != nil,
			ssmq.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SharedSpaceMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SharedSpaceMember{config: ssmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssmq.withSharedSpace; query != nil {
		if err := ssmq.loadSharedSpace(ctx, query, nodes, nil,
			func(n *SharedSpaceMember, e *SharedSpace) { n.Edges.SharedSpace = e }); err != nil {
			return nil, err
		}
	}
	if query := ssmq.withUser; query != nil {
		if err := ssmq.loadUser(ctx, query, nodes, nil,
			func(n *SharedSpaceMember, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ssmq.withGroup; query != nil {
		if err := ssmq.loadGroup(ctx, query, nodes, nil,
			func(n *SharedSpaceMember, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssmq *SharedSpaceMemberQuery) loadSharedSpace(ctx context.Context, query *SharedSpaceQuery, nodes []*SharedSpaceMember, init func(*SharedSpaceMember), assign func(*SharedSpaceMember, *SharedSpace)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedSpaceMember)
	for i := range nodes {
		fk := nodes[i].SharedSpaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sharedspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shared_space_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ssmq *SharedSpaceMemberQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SharedSpaceMember, init func(*SharedSpaceMember), assign func(*SharedSpaceMember, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedSpaceMember)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ssmq *SharedSpaceMemberQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*SharedSpaceMember, init func(*SharedSpaceMember), assign func(*SharedSpaceMember, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedSpaceMember)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssmq *SharedSpaceMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssmq.querySpec()
	_spec.Node.Columns = ssmq.ctx.Fields
	if len(ssmq.ctx.Fields) > 0 {
		_spec.Unique = ssmq.ctx.Unique != nil && *ssmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssmq.driver, _spec)
}

func (ssmq *SharedSpaceMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharedspacemember.Table, sharedspacemember.Columns, sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt))
	_spec.From = ssmq.sql
	if unique := ssmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssmq.path != nil {
		_spec.Unique = true
	}
	if fields := ssmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedspacemember.FieldID)
		for i := range fields {
			if fields[i] != sharedspacemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ssmq.withSharedSpace != nil {
			_spec.Node.AddColumnOnce(sharedspacemember.FieldSharedSpaceID)
		}
		if ssmq.withUser != nil {
			_spec.Node.AddColumnOnce(sharedspacemember.FieldUserID)
		}
		if ssmq.withGroup != nil {
			_spec.Node.AddColumnOnce(sharedspacemember.FieldGroupID)
		}
	}
	if ps := ssmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssmq *SharedSpaceMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssmq.driver.Dialect())
	t1 := builder.Table(sharedspacemember.Table)
	columns := ssmq.ctx.Fields
	if len(columns) == 0 {
		columns = sharedspacemember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssmq.sql != nil {
		selector = ssmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssmq.ctx.Unique != nil && *ssmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssmq.predicates {
		p(selector)
	}
	for _, p := range ssmq.order {
		p(selector)
	}
	if offset := ssmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SharedSpaceMemberGroupBy is the group-by builder for SharedSpaceMember entities.
type SharedSpaceMemberGroupBy struct {
	selector
	build *SharedSpaceMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssmgb *SharedSpaceMemberGroupBy) Aggregate(fns ...AggregateFunc) *SharedSpaceMemberGroupBy {
	ssmgb.fns = append(ssmgb.fns, fns...)
	return ssmgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssmgb *SharedSpaceMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssmgb.build.ctx, "GroupBy")
	if err := ssmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedSpaceMemberQuery, *SharedSpaceMemberGroupBy](ctx, ssmgb.build, ssmgb, ssmgb.build.inters, v)
}

func (ssmgb *SharedSpaceMemberGroupBy) sqlScan(ctx context.Context, root *SharedSpaceMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssmgb.fns))
	for _, fn := range ssmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssmgb.flds)+len(ssmgb.fns))
		for _, f := range *ssmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SharedSpaceMemberSelect is the builder for selecting fields of SharedSpaceMember entities.
type SharedSpaceMemberSelect struct {
	*SharedSpaceMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ssms *SharedSpaceMemberSelect) Aggregate(fns ...AggregateFunc) *SharedSpaceMemberSelect {
	ssms.fns = append(ssms.fns, fns...)
	return ssms
}

// Scan applies the selector query and scans the result into the given value.
func (ssms *SharedSpaceMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssms.ctx, "Select")
	if err := ssms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedSpaceMemberQuery, *SharedSpaceMemberSelect](ctx, ssms.SharedSpaceMemberQuery, ssms, ssms.inters, v)
}

func (ssms *SharedSpaceMemberSelect) sqlScan(ctx context.Context, root *SharedSpaceMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ssms.fns))
	for _, fn := range ssms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ssms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
