// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceMemberUpdate is the builder for updating SharedSpaceMember entities.
type SharedSpaceMemberUpdate struct {
	config
	hooks    []Hook
	mutation *SharedSpaceMemberMutation
}

// Where appends a list predicates to the SharedSpaceMemberUpdate builder.
func (ssmu *SharedSpaceMemberUpdate) Where(ps ...predicate.SharedSpaceMember) *SharedSpaceMemberUpdate {
	ssmu.mutation.Where(ps...)
	return ssmu
}

// SetUpdatedAt sets the "updated_at" field.
func (ssmu *SharedSpaceMemberUpdate) SetUpdatedAt(t time.Time) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetUpdatedAt(t)
	return ssmu
}

// SetDeletedAt sets the "deleted_at" field.
func (ssmu *SharedSpaceMemberUpdate) SetDeletedAt(t time.Time) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetDeletedAt(t)
	return ssmu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssmu *SharedSpaceMemberUpdate) SetNillableDeletedAt(t *time.Time) *SharedSpaceMemberUpdate {
	if t != nil {
		ssmu.SetDeletedAt(*t)
	}
	return ssmu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ssmu *SharedSpaceMemberUpdate) ClearDeletedAt() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearDeletedAt()
	return ssmu
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (ssmu *SharedSpaceMemberUpdate) SetSharedSpaceID(i int) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetSharedSpaceID(i)
	return ssmu
}

// SetNillableSharedSpaceID sets the "shared_space_id" field if the given value is not nil.
func (ssmu *SharedSpaceMemberUpdate) SetNillableSharedSpaceID(i *int) *SharedSpaceMemberUpdate {
	if i != nil {
		ssmu.SetSharedSpaceID(*i)
	}
	return ssmu
}

// SetUserID sets the "user_id" field.
func (ssmu *SharedSpaceMemberUpdate) SetUserID(i int) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetUserID(i)
	return ssmu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ssmu *SharedSpaceMemberUpdate) SetNillableUserID(i *int) *SharedSpaceMemberUpdate {
	if i != nil {
		ssmu.SetUserID(*i)
	}
	return ssmu
}

// ClearUserID clears the value of the "user_id" field.
func (ssmu *SharedSpaceMemberUpdate) ClearUserID() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearUserID()
	return ssmu
}

// SetGroupID sets the "group_id" field.
func (ssmu *SharedSpaceMemberUpdate) SetGroupID(i int) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetGroupID(i)
	return ssmu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (ssmu *SharedSpaceMemberUpdate) SetNillableGroupID(i *int) *SharedSpaceMemberUpdate {
	if i != nil {
		ssmu.SetGroupID(*i)
	}
	return ssmu
}

// ClearGroupID clears the value of the "group_id" field.
func (ssmu *SharedSpaceMemberUpdate) ClearGroupID() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearGroupID()
	return ssmu
}

// SetRole sets the "role" field.
func (ssmu *SharedSpaceMemberUpdate) SetRole(s sharedspacemember.Role) *SharedSpaceMemberUpdate {
	ssmu.mutation.SetRole(s)
	return ssmu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ssmu *SharedSpaceMemberUpdate) SetNillableRole(s *sharedspacemember.Role) *SharedSpaceMemberUpdate {
	if s != nil {
		ssmu.SetRole(*s)
	}
	return ssmu
}

// SetSharedSpace sets the "shared_space" edge to the SharedSpace entity.
func (ssmu *SharedSpaceMemberUpdate) SetSharedSpace(s *SharedSpace) *SharedSpaceMemberUpdate {
	return ssmu.SetSharedSpaceID(s.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ssmu *SharedSpaceMemberUpdate) SetUser(u *User) *SharedSpaceMemberUpdate {
	return ssmu.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (ssmu *SharedSpaceMemberUpdate) SetGroup(g *Group) *SharedSpaceMemberUpdate {
	return ssmu.SetGroupID(g.ID)
}

// Mutation returns the SharedSpaceMemberMutation object of the builder.
func (ssmu *SharedSpaceMemberUpdate) Mutation() *SharedSpaceMemberMutation {
	return ssmu.mutation
}

// ClearSharedSpace clears the "shared_space" edge to the SharedSpace entity.
func (ssmu *SharedSpaceMemberUpdate) ClearSharedSpace() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearSharedSpace()
	return ssmu
}

// ClearUser clears the "user" edge to the User entity.
func (ssmu *SharedSpaceMemberUpdate) ClearUser() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearUser()
	return ssmu
}

// ClearGroup clears the "group" edge to the Group entity.
func (ssmu *SharedSpaceMemberUpdate) ClearGroup() *SharedSpaceMemberUpdate {
	ssmu.mutation.ClearGroup()
	return ssmu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ssmu *SharedSpaceMemberUpdate) Save(ctx context.Context) (int, error) {
	if err := ssmu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ssmu.sqlSave, ssmu.mutation, ssmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssmu *SharedSpaceMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := ssmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ssmu *SharedSpaceMemberUpdate) Exec(ctx context.Context) error {
	_, err := ssmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmu *SharedSpaceMemberUpdate) ExecX(ctx context.Context) {
	if err := ssmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssmu *SharedSpaceMemberUpdate) defaults() error {
	if _, ok := ssmu.mutation.UpdatedAt(); !ok {
		if sharedspacemember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspacemember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspacemember.UpdateDefaultUpdatedAt()
		ssmu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssmu *SharedSpaceMemberUpdate) check() error {
	if v, ok := ssmu.mutation.Role(); ok {
		if err := sharedspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SharedSpaceMember.role": %w`, err)}
		}
	}
	if _, ok := ssmu.mutation.SharedSpaceID(); ssmu.mutation.SharedSpaceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SharedSpaceMember.shared_space"`)
	}
	return nil
}

func (ssmu *SharedSpaceMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ssmu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedspacemember.Table, sharedspacemember.Columns, sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt))
	if ps := ssmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssmu.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspacemember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssmu.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspacemember.FieldDeletedAt, field.TypeTime, value)
	}
	if ssmu.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedspacemember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ssmu.mutation.Role(); ok {
		_spec.SetField(sharedspacemember.FieldRole, field.TypeEnum, value)
	}
	if ssmu.mutation.SharedSpaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.SharedSpaceTable,
			Columns: []string{sharedspacemember.SharedSpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmu.mutation.SharedSpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.SharedSpaceTable,
			Columns: []string{sharedspacemember.SharedSpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssmu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.UserTable,
			Columns: []string{sharedspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.UserTable,
			Columns: []string{sharedspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssmu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.GroupTable,
			Columns: []string{sharedspacemember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.GroupTable,
			Columns: []string{sharedspacemember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ssmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ssmu.mutation.done = true
	return n, nil
}

// SharedSpaceMemberUpdateOne is the builder for updating a single SharedSpaceMember entity.
type SharedSpaceMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedSpaceMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetUpdatedAt(t time.Time) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetUpdatedAt(t)
	return ssmuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetDeletedAt(t time.Time) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetDeletedAt(t)
	return ssmuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssmuo *SharedSpaceMemberUpdateOne) SetNillableDeletedAt(t *time.Time) *SharedSpaceMemberUpdateOne {
	if t != nil {
		ssmuo.SetDeletedAt(*t)
	}
	return ssmuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearDeletedAt() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearDeletedAt()
	return ssmuo
}

// SetSharedSpaceID sets the "shared_space_id" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetSharedSpaceID(i int) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetSharedSpaceID(i)
	return ssmuo
}

// SetNillableSharedSpaceID sets the "shared_space_id" field if the given value is not nil.
func (ssmuo *SharedSpaceMemberUpdateOne) SetNillableSharedSpaceID(i *int) *SharedSpaceMemberUpdateOne {
	if i != nil {
		ssmuo.SetSharedSpaceID(*i)
	}
	return ssmuo
}

// SetUserID sets the "user_id" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetUserID(i int) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetUserID(i)
	return ssmuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ssmuo *SharedSpaceMemberUpdateOne) SetNillableUserID(i *int) *SharedSpaceMemberUpdateOne {
	if i != nil {
		ssmuo.SetUserID(*i)
	}
	return ssmuo
}

// ClearUserID clears the value of the "user_id" field.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearUserID() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearUserID()
	return ssmuo
}

// SetGroupID sets the "group_id" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetGroupID(i int) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetGroupID(i)
	return ssmuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (ssmuo *SharedSpaceMemberUpdateOne) SetNillableGroupID(i *int) *SharedSpaceMemberUpdateOne {
	if i != nil {
		ssmuo.SetGroupID(*i)
	}
	return ssmuo
}

// ClearGroupID clears the value of the "group_id" field.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearGroupID() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearGroupID()
	return ssmuo
}

// SetRole sets the "role" field.
func (ssmuo *SharedSpaceMemberUpdateOne) SetRole(s sharedspacemember.Role) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.SetRole(s)
	return ssmuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ssmuo *SharedSpaceMemberUpdateOne) SetNillableRole(s *sharedspacemember.Role) *SharedSpaceMemberUpdateOne {
	if s != nil {
		ssmuo.SetRole(*s)
	}
	return ssmuo
}

// SetSharedSpace sets the "shared_space" edge to the SharedSpace entity.
func (ssmuo *SharedSpaceMemberUpdateOne) SetSharedSpace(s *SharedSpace) *SharedSpaceMemberUpdateOne {
	return ssmuo.SetSharedSpaceID(s.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ssmuo *SharedSpaceMemberUpdateOne) SetUser(u *User) *SharedSpaceMemberUpdateOne {
	return ssmuo.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (ssmuo *SharedSpaceMemberUpdateOne) SetGroup(g *Group) *SharedSpaceMemberUpdateOne {
	return ssmuo.SetGroupID(g.ID)
}

// Mutation returns the SharedSpaceMemberMutation object of the builder.
func (ssmuo *SharedSpaceMemberUpdateOne) Mutation() *SharedSpaceMemberMutation {
	return ssmuo.mutation
}

// ClearSharedSpace clears the "shared_space" edge to the SharedSpace entity.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearSharedSpace() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearSharedSpace()
	return ssmuo
}

// ClearUser clears the "user" edge to the User entity.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearUser() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearUser()
	return ssmuo
}

// ClearGroup clears the "group" edge to the Group entity.
func (ssmuo *SharedSpaceMemberUpdateOne) ClearGroup() *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.ClearGroup()
	return ssmuo
}

// Where appends a list predicates to the SharedSpaceMemberUpdate builder.
func (ssmuo *SharedSpaceMemberUpdateOne) Where(ps ...predicate.SharedSpaceMember) *SharedSpaceMemberUpdateOne {
	ssmuo.mutation.Where(ps...)
	return ssmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ssmuo *SharedSpaceMemberUpdateOne) Select(field string, fields ...string) *SharedSpaceMemberUpdateOne {
	ssmuo.fields = append([]string{field}, fields...)
	return ssmuo
}

// Save executes the query and returns the updated SharedSpaceMember entity.
func (ssmuo *SharedSpaceMemberUpdateOne) Save(ctx context.Context) (*SharedSpaceMember, error) {
	if err := ssmuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ssmuo.sqlSave, ssmuo.mutation, ssmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssmuo *SharedSpaceMemberUpdateOne) SaveX(ctx context.Context) *SharedSpaceMember {
	node, err := ssmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ssmuo *SharedSpaceMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := ssmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmuo *SharedSpaceMemberUpdateOne) ExecX(ctx context.Context) {
	if err := ssmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssmuo *SharedSpaceMemberUpdateOne) defaults() error {
	if _, ok := ssmuo.mutation.UpdatedAt(); !ok {
		if sharedspacemember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspacemember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspacemember.UpdateDefaultUpdatedAt()
		ssmuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssmuo *SharedSpaceMemberUpdateOne) check() error {
	if v, ok := ssmuo.mutation.Role(); ok {
		if err := sharedspacemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SharedSpaceMember.role": %w`, err)}
		}
	}
	if _, ok := ssmuo.mutation.SharedSpaceID(); ssmuo.mutation.SharedSpaceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SharedSpaceMember.shared_space"`)
	}
	return nil
}

func (ssmuo *SharedSpaceMemberUpdateOne) sqlSave(ctx context.Context) (_node *SharedSpaceMember, err error) {
	if err := ssmuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedspacemember.Table, sharedspacemember.Columns, sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt))
	id, ok := ssmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedSpaceMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ssmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedspacemember.FieldID)
		for _, f := range fields {
			if !sharedspacemember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedspacemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ssmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssmuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspacemember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssmuo.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspacemember.FieldDeletedAt, field.TypeTime, value)
	}
	if ssmuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedspacemember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ssmuo.mutation.Role(); ok {
		_spec.SetField(sharedspacemember.FieldRole, field.TypeEnum, value)
	}
	if ssmuo.mutation.SharedSpaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.SharedSpaceTable,
			Columns: []string{sharedspacemember.SharedSpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmuo.mutation.SharedSpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.SharedSpaceTable,
			Columns: []string{sharedspacemember.SharedSpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssmuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.UserTable,
			Columns: []string{sharedspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.UserTable,
			Columns: []string{sharedspacemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssmuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.GroupTable,
			Columns: []string{sharedspacemember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssmuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspacemember.GroupTable,
			Columns: []string{sharedspacemember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SharedSpaceMember{config: ssmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ssmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedspacemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ssmuo.mutation.done = true
	return _node, nil
}
