// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
)

// SharedSpaceMemberDelete is the builder for deleting a SharedSpaceMember entity.
type SharedSpaceMemberDelete struct {
	config
	hooks    []Hook
	mutation *SharedSpaceMemberMutation
}

// Where appends a list predicates to the SharedSpaceMemberDelete builder.
func (ssmd *SharedSpaceMemberDelete) Where(ps ...predicate.SharedSpaceMember) *SharedSpaceMemberDelete {
	ssmd.mutation.Where(ps...)
	return ssmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ssmd *SharedSpaceMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ssmd.sqlExec, ssmd.mutation, ssmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmd *SharedSpaceMemberDelete) ExecX(ctx context.Context) int {
	n, err := ssmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ssmd *SharedSpaceMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sharedspacemember.Table, sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt))
	if ps := ssmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ssmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ssmd.mutation.done = true
	return affected, err
}

// SharedSpaceMemberDeleteOne is the builder for deleting a single SharedSpaceMember entity.
type SharedSpaceMemberDeleteOne struct {
	ssmd *SharedSpaceMemberDelete
}

// Where appends a list predicates to the SharedSpaceMemberDelete builder.
func (ssmdo *SharedSpaceMemberDeleteOne) Where(ps ...predicate.SharedSpaceMember) *SharedSpaceMemberDeleteOne {
	ssmdo.ssmd.mutation.Where(ps...)
	return ssmdo
}

// Exec executes the deletion query.
func (ssmdo *SharedSpaceMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := ssmdo.ssmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sharedspacemember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ssmdo *SharedSpaceMemberDeleteOne) ExecX(ctx context.Context) {
	if err := ssmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
