// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceQuery is the builder for querying SharedSpace entities.
type SharedSpaceQuery struct {
	config
	ctx          *QueryContext
	order        []sharedspace.OrderOption
	inters       []Interceptor
	predicates   []predicate.SharedSpace
	withOwner    *UserQuery
	withMembers  *SharedSpaceMemberQuery
	withRootFile *FileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SharedSpaceQuery builder.
func (ssq *SharedSpaceQuery) Where(ps ...predicate.SharedSpace) *SharedSpaceQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SharedSpaceQuery) Limit(limit int) *SharedSpaceQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SharedSpaceQuery) Offset(offset int) *SharedSpaceQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SharedSpaceQuery) Unique(unique bool) *SharedSpaceQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SharedSpaceQuery) Order(o ...sharedspace.OrderOption) *SharedSpaceQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QueryOwner chains the current query on the "owner" edge.
func (ssq *SharedSpaceQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspace.Table, sharedspace.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedspace.OwnerTable, sharedspace.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMembers chains the current query on the "members" edge.
func (ssq *SharedSpaceQuery) QueryMembers() *SharedSpaceMemberQuery {
	query := (&SharedSpaceMemberClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspace.Table, sharedspace.FieldID, selector),
			sqlgraph.To(sharedspacemember.Table, sharedspacemember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sharedspace.MembersTable, sharedspace.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRootFile chains the current query on the "root_file" edge.
func (ssq *SharedSpaceQuery) QueryRootFile() *FileQuery {
	query := (&FileClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedspace.Table, sharedspace.FieldID, selector),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sharedspace.RootFileTable, sharedspace.RootFileColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SharedSpace entity from the query.
// Returns a *NotFoundError when no SharedSpace was found.
func (ssq *SharedSpaceQuery) First(ctx context.Context) (*SharedSpace, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharedspace.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SharedSpaceQuery) FirstX(ctx context.Context) *SharedSpace {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SharedSpace ID from the query.
// Returns a *NotFoundError when no SharedSpace ID was found.
func (ssq *SharedSpaceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharedspace.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SharedSpaceQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SharedSpace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SharedSpace entity is found.
// Returns a *NotFoundError when no SharedSpace entities are found.
func (ssq *SharedSpaceQuery) Only(ctx context.Context) (*SharedSpace, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharedspace.Label}
	default:
		return nil, &NotSingularError{sharedspace.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SharedSpaceQuery) OnlyX(ctx context.Context) *SharedSpace {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SharedSpace ID in the query.
// Returns a *NotSingularError when more than one SharedSpace ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SharedSpaceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharedspace.Label}
	default:
		err = &NotSingularError{sharedspace.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SharedSpaceQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SharedSpaces.
func (ssq *SharedSpaceQuery) All(ctx context.Context) ([]*SharedSpace, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SharedSpace, *SharedSpaceQuery]()
	return withInterceptors[[]*SharedSpace](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SharedSpaceQuery) AllX(ctx context.Context) []*SharedSpace {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SharedSpace IDs.
func (ssq *SharedSpaceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err = ssq.Select(sharedspace.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SharedSpaceQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SharedSpaceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SharedSpaceQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SharedSpaceQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SharedSpaceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SharedSpaceQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SharedSpaceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SharedSpaceQuery) Clone() *SharedSpaceQuery {
	if ssq == nil {
		return nil
	}
	return &SharedSpaceQuery{
		config:       ssq.config,
		ctx:          ssq.ctx.Clone(),
		order:        append([]sharedspace.OrderOption{}, ssq.order...),
		inters:       append([]Interceptor{}, ssq.inters...),
		predicates:   append([]predicate.SharedSpace{}, ssq.predicates...),
		withOwner:    ssq.withOwner.Clone(),
		withMembers:  ssq.withMembers.Clone(),
		withRootFile: ssq.withRootFile.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SharedSpaceQuery) WithOwner(opts ...func(*UserQuery)) *SharedSpaceQuery {
	query := (&UserClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withOwner = query
	return ssq
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SharedSpaceQuery) WithMembers(opts ...func(*SharedSpaceMemberQuery)) *SharedSpaceQuery {
	query := (&SharedSpaceMemberClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withMembers = query
	return ssq
}

// WithRootFile tells the query-builder to eager-load the nodes that are connected to
// the "root_file" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SharedSpaceQuery) WithRootFile(opts ...func(*FileQuery)) *SharedSpaceQuery {
	query := (&FileClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withRootFile = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SharedSpace.Query().
//		GroupBy(sharedspace.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *SharedSpaceQuery) GroupBy(field string, fields ...string) *SharedSpaceGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SharedSpaceGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = sharedspace.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SharedSpace.Query().
//		Select(sharedspace.FieldCreatedAt).
//		Scan(ctx, &v)
func (ssq *SharedSpaceQuery) Select(fields ...string) *SharedSpaceSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SharedSpaceSelect{SharedSpaceQuery: ssq}
	sbuild.label = sharedspace.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SharedSpaceSelect configured with the given aggregations.
func (ssq *SharedSpaceQuery) Aggregate(fns ...AggregateFunc) *SharedSpaceSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SharedSpaceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !sharedspace.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SharedSpaceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SharedSpace, error) {
	var (
		nodes       = []*SharedSpace{}
		_spec       = ssq.querySpec()
		loadedTypes = [3]bool{
			ssq.withOwner != nil,
			ssq.withMembers != nil,
			ssq.withRootFile != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SharedSpace).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SharedSpace{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withOwner; query != nil {
		if err := ssq.loadOwner(ctx, query, nodes, nil,
			func(n *SharedSpace, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := ssq.withMembers; query != nil {
		if err := ssq.loadMembers(ctx, query, nodes,
			func(n *SharedSpace) { n.Edges.Members = []*SharedSpaceMember{} },
			func(n *SharedSpace, e *SharedSpaceMember) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	if query := ssq.withRootFile; query != nil {
		if err := ssq.loadRootFile(ctx, query, nodes, nil,
			func(n *SharedSpace, e *File) { n.Edges.RootFile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *SharedSpaceQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*SharedSpace, init func(*SharedSpace), assign func(*SharedSpace, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedSpace)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ssq *SharedSpaceQuery) loadMembers(ctx context.Context, query *SharedSpaceMemberQuery, nodes []*SharedSpace, init func(*SharedSpace), assign func(*SharedSpace, *SharedSpaceMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SharedSpace)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sharedspacemember.FieldSharedSpaceID)
	}
	query.Where(predicate.SharedSpaceMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sharedspace.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SharedSpaceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "shared_space_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (ssq *SharedSpaceQuery) loadRootFile(ctx context.Context, query *FileQuery, nodes []*SharedSpace, init func(*SharedSpace), assign func(*SharedSpace, *File)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedSpace)
	for i := range nodes {
		fk := nodes[i].RootFileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(file.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "root_file_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssq *SharedSpaceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SharedSpaceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharedspace.Table, sharedspace.Columns, sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedspace.FieldID)
		for i := range fields {
			if fields[i] != sharedspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ssq.withOwner != nil {
			_spec.Node.AddColumnOnce(sharedspace.FieldOwnerID)
		}
		if ssq.withRootFile != nil {
			_spec.Node.AddColumnOnce(sharedspace.FieldRootFileID)
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SharedSpaceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(sharedspace.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = sharedspace.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SharedSpaceGroupBy is the group-by builder for SharedSpace entities.
type SharedSpaceGroupBy struct {
	selector
	build *SharedSpaceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SharedSpaceGroupBy) Aggregate(fns ...AggregateFunc) *SharedSpaceGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SharedSpaceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedSpaceQuery, *SharedSpaceGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SharedSpaceGroupBy) sqlScan(ctx context.Context, root *SharedSpaceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SharedSpaceSelect is the builder for selecting fields of SharedSpace entities.
type SharedSpaceSelect struct {
	*SharedSpaceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SharedSpaceSelect) Aggregate(fns ...AggregateFunc) *SharedSpaceSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SharedSpaceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedSpaceQuery, *SharedSpaceSelect](ctx, sss.SharedSpaceQuery, sss, sss.inters, v)
}

func (sss *SharedSpaceSelect) sqlScan(ctx context.Context, root *SharedSpaceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
