// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspace"
	"github.com/cloudreve/Cloudreve/v4/ent/sharedspacemember"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharedSpaceUpdate is the builder for updating SharedSpace entities.
type SharedSpaceUpdate struct {
	config
	hooks    []Hook
	mutation *SharedSpaceMutation
}

// Where appends a list predicates to the SharedSpaceUpdate builder.
func (ssu *SharedSpaceUpdate) Where(ps ...predicate.SharedSpace) *SharedSpaceUpdate {
	ssu.mutation.Where(ps...)
	return ssu
}

// SetUpdatedAt sets the "updated_at" field.
func (ssu *SharedSpaceUpdate) SetUpdatedAt(t time.Time) *SharedSpaceUpdate {
	ssu.mutation.SetUpdatedAt(t)
	return ssu
}

// SetDeletedAt sets the "deleted_at" field.
func (ssu *SharedSpaceUpdate) SetDeletedAt(t time.Time) *SharedSpaceUpdate {
	ssu.mutation.SetDeletedAt(t)
	return ssu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssu *SharedSpaceUpdate) SetNillableDeletedAt(t *time.Time) *SharedSpaceUpdate {
	if t != nil {
		ssu.SetDeletedAt(*t)
	}
	return ssu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ssu *SharedSpaceUpdate) ClearDeletedAt() *SharedSpaceUpdate {
	ssu.mutation.ClearDeletedAt()
	return ssu
}

// SetName sets the "name" field.
func (ssu *SharedSpaceUpdate) SetName(s string) *SharedSpaceUpdate {
	ssu.mutation.SetName(s)
	return ssu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ssu *SharedSpaceUpdate) SetNillableName(s *string) *SharedSpaceUpdate {
	if s != nil {
		ssu.SetName(*s)
	}
	return ssu
}

// SetDescription sets the "description" field.
func (ssu *SharedSpaceUpdate) SetDescription(s string) *SharedSpaceUpdate {
	ssu.mutation.SetDescription(s)
	return ssu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ssu *SharedSpaceUpdate) SetNillableDescription(s *string) *SharedSpaceUpdate {
	if s != nil {
		ssu.SetDescription(*s)
	}
	return ssu
}

// ClearDescription clears the value of the "description" field.
func (ssu *SharedSpaceUpdate) ClearDescription() *SharedSpaceUpdate {
	ssu.mutation.ClearDescription()
	return ssu
}

// SetOwnerID sets the "owner_id" field.
func (ssu *SharedSpaceUpdate) SetOwnerID(i int) *SharedSpaceUpdate {
	ssu.mutation.SetOwnerID(i)
	return ssu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (ssu *SharedSpaceUpdate) SetNillableOwnerID(i *int) *SharedSpaceUpdate {
	if i != nil {
		ssu.SetOwnerID(*i)
	}
	return ssu
}

// SetRootFileID sets the "root_file_id" field.
func (ssu *SharedSpaceUpdate) SetRootFileID(i int) *SharedSpaceUpdate {
	ssu.mutation.SetRootFileID(i)
	return ssu
}

// SetNillableRootFileID sets the "root_file_id" field if the given value is not nil.
func (ssu *SharedSpaceUpdate) SetNillableRootFileID(i *int) *SharedSpaceUpdate {
	if i != nil {
		ssu.SetRootFileID(*i)
	}
	return ssu
}

// ClearRootFileID clears the value of the "root_file_id" field.
func (ssu *SharedSpaceUpdate) ClearRootFileID() *SharedSpaceUpdate {
	ssu.mutation.ClearRootFileID()
	return ssu
}

// SetOwner sets the "owner" edge to the User entity.
func (ssu *SharedSpaceUpdate) SetOwner(u *User) *SharedSpaceUpdate {
	return ssu.SetOwnerID(u.ID)
}

// AddMemberIDs adds the "members" edge to the SharedSpaceMember entity by IDs.
func (ssu *SharedSpaceUpdate) AddMemberIDs(ids ...int) *SharedSpaceUpdate {
	ssu.mutation.AddMemberIDs(ids...)
	return ssu
}

// AddMembers adds the "members" edges to the SharedSpaceMember entity.
func (ssu *SharedSpaceUpdate) AddMembers(s ...*SharedSpaceMember) *SharedSpaceUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ssu.AddMemberIDs(ids...)
}

// SetRootFile sets the "root_file" edge to the File entity.
func (ssu *SharedSpaceUpdate) SetRootFile(f *File) *SharedSpaceUpdate {
	return ssu.SetRootFileID(f.ID)
}

// Mutation returns the SharedSpaceMutation object of the builder.
func (ssu *SharedSpaceUpdate) Mutation() *SharedSpaceMutation {
	return ssu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (ssu *SharedSpaceUpdate) ClearOwner() *SharedSpaceUpdate {
	ssu.mutation.ClearOwner()
	return ssu
}

// ClearMembers clears all "members" edges to the SharedSpaceMember entity.
func (ssu *SharedSpaceUpdate) ClearMembers() *SharedSpaceUpdate {
	ssu.mutation.ClearMembers()
	return ssu
}

// RemoveMemberIDs removes the "members" edge to SharedSpaceMember entities by IDs.
func (ssu *SharedSpaceUpdate) RemoveMemberIDs(ids ...int) *SharedSpaceUpdate {
	ssu.mutation.RemoveMemberIDs(ids...)
	return ssu
}

// RemoveMembers removes "members" edges to SharedSpaceMember entities.
func (ssu *SharedSpaceUpdate) RemoveMembers(s ...*SharedSpaceMember) *SharedSpaceUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ssu.RemoveMemberIDs(ids...)
}

// ClearRootFile clears the "root_file" edge to the File entity.
func (ssu *SharedSpaceUpdate) ClearRootFile() *SharedSpaceUpdate {
	ssu.mutation.ClearRootFile()
	return ssu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ssu *SharedSpaceUpdate) Save(ctx context.Context) (int, error) {
	if err := ssu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ssu.sqlSave, ssu.mutation, ssu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssu *SharedSpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := ssu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ssu *SharedSpaceUpdate) Exec(ctx context.Context) error {
	_, err := ssu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssu *SharedSpaceUpdate) ExecX(ctx context.Context) {
	if err := ssu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssu *SharedSpaceUpdate) defaults() error {
	if _, ok := ssu.mutation.UpdatedAt(); !ok {
		if sharedspace.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspace.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspace.UpdateDefaultUpdatedAt()
		ssu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssu *SharedSpaceUpdate) check() error {
	if v, ok := ssu.mutation.Name(); ok {
		if err := sharedspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.name": %w`, err)}
		}
	}
	if v, ok := ssu.mutation.Description(); ok {
		if err := sharedspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.description": %w`, err)}
		}
	}
	if _, ok := ssu.mutation.OwnerID(); ssu.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SharedSpace.owner"`)
	}
	return nil
}

func (ssu *SharedSpaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ssu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedspace.Table, sharedspace.Columns, sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt))
	if ps := ssu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssu.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssu.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspace.FieldDeletedAt, field.TypeTime, value)
	}
	if ssu.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedspace.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ssu.mutation.Name(); ok {
		_spec.SetField(sharedspace.FieldName, field.TypeString, value)
	}
	if value, ok := ssu.mutation.Description(); ok {
		_spec.SetField(sharedspace.FieldDescription, field.TypeString, value)
	}
	if ssu.mutation.DescriptionCleared() {
		_spec.ClearField(sharedspace.FieldDescription, field.TypeString)
	}
	if ssu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspace.OwnerTable,
			Columns: []string{sharedspace.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspace.OwnerTable,
			Columns: []string{sharedspace.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssu.mutation.RemovedMembersIDs(); len(nodes) > 0 && !ssu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssu.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssu.mutation.RootFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sharedspace.RootFileTable,
			Columns: []string{sharedspace.RootFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssu.mutation.RootFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sharedspace.RootFileTable,
			Columns: []string{sharedspace.RootFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ssu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ssu.mutation.done = true
	return n, nil
}

// SharedSpaceUpdateOne is the builder for updating a single SharedSpace entity.
type SharedSpaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SharedSpaceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ssuo *SharedSpaceUpdateOne) SetUpdatedAt(t time.Time) *SharedSpaceUpdateOne {
	ssuo.mutation.SetUpdatedAt(t)
	return ssuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ssuo *SharedSpaceUpdateOne) SetDeletedAt(t time.Time) *SharedSpaceUpdateOne {
	ssuo.mutation.SetDeletedAt(t)
	return ssuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ssuo *SharedSpaceUpdateOne) SetNillableDeletedAt(t *time.Time) *SharedSpaceUpdateOne {
	if t != nil {
		ssuo.SetDeletedAt(*t)
	}
	return ssuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ssuo *SharedSpaceUpdateOne) ClearDeletedAt() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearDeletedAt()
	return ssuo
}

// SetName sets the "name" field.
func (ssuo *SharedSpaceUpdateOne) SetName(s string) *SharedSpaceUpdateOne {
	ssuo.mutation.SetName(s)
	return ssuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ssuo *SharedSpaceUpdateOne) SetNillableName(s *string) *SharedSpaceUpdateOne {
	if s != nil {
		ssuo.SetName(*s)
	}
	return ssuo
}

// SetDescription sets the "description" field.
func (ssuo *SharedSpaceUpdateOne) SetDescription(s string) *SharedSpaceUpdateOne {
	ssuo.mutation.SetDescription(s)
	return ssuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ssuo *SharedSpaceUpdateOne) SetNillableDescription(s *string) *SharedSpaceUpdateOne {
	if s != nil {
		ssuo.SetDescription(*s)
	}
	return ssuo
}

// ClearDescription clears the value of the "description" field.
func (ssuo *SharedSpaceUpdateOne) ClearDescription() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearDescription()
	return ssuo
}

// SetOwnerID sets the "owner_id" field.
func (ssuo *SharedSpaceUpdateOne) SetOwnerID(i int) *SharedSpaceUpdateOne {
	ssuo.mutation.SetOwnerID(i)
	return ssuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (ssuo *SharedSpaceUpdateOne) SetNillableOwnerID(i *int) *SharedSpaceUpdateOne {
	if i != nil {
		ssuo.SetOwnerID(*i)
	}
	return ssuo
}

// SetRootFileID sets the "root_file_id" field.
func (ssuo *SharedSpaceUpdateOne) SetRootFileID(i int) *SharedSpaceUpdateOne {
	ssuo.mutation.SetRootFileID(i)
	return ssuo
}

// SetNillableRootFileID sets the "root_file_id" field if the given value is not nil.
func (ssuo *SharedSpaceUpdateOne) SetNillableRootFileID(i *int) *SharedSpaceUpdateOne {
	if i != nil {
		ssuo.SetRootFileID(*i)
	}
	return ssuo
}

// ClearRootFileID clears the value of the "root_file_id" field.
func (ssuo *SharedSpaceUpdateOne) ClearRootFileID() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearRootFileID()
	return ssuo
}

// SetOwner sets the "owner" edge to the User entity.
func (ssuo *SharedSpaceUpdateOne) SetOwner(u *User) *SharedSpaceUpdateOne {
	return ssuo.SetOwnerID(u.ID)
}

// AddMemberIDs adds the "members" edge to the SharedSpaceMember entity by IDs.
func (ssuo *SharedSpaceUpdateOne) AddMemberIDs(ids ...int) *SharedSpaceUpdateOne {
	ssuo.mutation.AddMemberIDs(ids...)
	return ssuo
}

// AddMembers adds the "members" edges to the SharedSpaceMember entity.
func (ssuo *SharedSpaceUpdateOne) AddMembers(s ...*SharedSpaceMember) *SharedSpaceUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ssuo.AddMemberIDs(ids...)
}

// SetRootFile sets the "root_file" edge to the File entity.
func (ssuo *SharedSpaceUpdateOne) SetRootFile(f *File) *SharedSpaceUpdateOne {
	return ssuo.SetRootFileID(f.ID)
}

// Mutation returns the SharedSpaceMutation object of the builder.
func (ssuo *SharedSpaceUpdateOne) Mutation() *SharedSpaceMutation {
	return ssuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (ssuo *SharedSpaceUpdateOne) ClearOwner() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearOwner()
	return ssuo
}

// ClearMembers clears all "members" edges to the SharedSpaceMember entity.
func (ssuo *SharedSpaceUpdateOne) ClearMembers() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearMembers()
	return ssuo
}

// RemoveMemberIDs removes the "members" edge to SharedSpaceMember entities by IDs.
func (ssuo *SharedSpaceUpdateOne) RemoveMemberIDs(ids ...int) *SharedSpaceUpdateOne {
	ssuo.mutation.RemoveMemberIDs(ids...)
	return ssuo
}

// RemoveMembers removes "members" edges to SharedSpaceMember entities.
func (ssuo *SharedSpaceUpdateOne) RemoveMembers(s ...*SharedSpaceMember) *SharedSpaceUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ssuo.RemoveMemberIDs(ids...)
}

// ClearRootFile clears the "root_file" edge to the File entity.
func (ssuo *SharedSpaceUpdateOne) ClearRootFile() *SharedSpaceUpdateOne {
	ssuo.mutation.ClearRootFile()
	return ssuo
}

// Where appends a list predicates to the SharedSpaceUpdate builder.
func (ssuo *SharedSpaceUpdateOne) Where(ps ...predicate.SharedSpace) *SharedSpaceUpdateOne {
	ssuo.mutation.Where(ps...)
	return ssuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ssuo *SharedSpaceUpdateOne) Select(field string, fields ...string) *SharedSpaceUpdateOne {
	ssuo.fields = append([]string{field}, fields...)
	return ssuo
}

// Save executes the query and returns the updated SharedSpace entity.
func (ssuo *SharedSpaceUpdateOne) Save(ctx context.Context) (*SharedSpace, error) {
	if err := ssuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ssuo.sqlSave, ssuo.mutation, ssuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssuo *SharedSpaceUpdateOne) SaveX(ctx context.Context) *SharedSpace {
	node, err := ssuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ssuo *SharedSpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := ssuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssuo *SharedSpaceUpdateOne) ExecX(ctx context.Context) {
	if err := ssuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssuo *SharedSpaceUpdateOne) defaults() error {
	if _, ok := ssuo.mutation.UpdatedAt(); !ok {
		if sharedspace.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sharedspace.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sharedspace.UpdateDefaultUpdatedAt()
		ssuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ssuo *SharedSpaceUpdateOne) check() error {
	if v, ok := ssuo.mutation.Name(); ok {
		if err := sharedspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.name": %w`, err)}
		}
	}
	if v, ok := ssuo.mutation.Description(); ok {
		if err := sharedspace.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SharedSpace.description": %w`, err)}
		}
	}
	if _, ok := ssuo.mutation.OwnerID(); ssuo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SharedSpace.owner"`)
	}
	return nil
}

func (ssuo *SharedSpaceUpdateOne) sqlSave(ctx context.Context) (_node *SharedSpace, err error) {
	if err := ssuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedspace.Table, sharedspace.Columns, sqlgraph.NewFieldSpec(sharedspace.FieldID, field.TypeInt))
	id, ok := ssuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedSpace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ssuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedspace.FieldID)
		for _, f := range fields {
			if !sharedspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ssuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssuo.mutation.UpdatedAt(); ok {
		_spec.SetField(sharedspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssuo.mutation.DeletedAt(); ok {
		_spec.SetField(sharedspace.FieldDeletedAt, field.TypeTime, value)
	}
	if ssuo.mutation.DeletedAtCleared() {
		_spec.ClearField(sharedspace.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ssuo.mutation.Name(); ok {
		_spec.SetField(sharedspace.FieldName, field.TypeString, value)
	}
	if value, ok := ssuo.mutation.Description(); ok {
		_spec.SetField(sharedspace.FieldDescription, field.TypeString, value)
	}
	if ssuo.mutation.DescriptionCleared() {
		_spec.ClearField(sharedspace.FieldDescription, field.TypeString)
	}
	if ssuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspace.OwnerTable,
			Columns: []string{sharedspace.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedspace.OwnerTable,
			Columns: []string{sharedspace.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssuo.mutation.RemovedMembersIDs(); len(nodes) > 0 && !ssuo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssuo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sharedspace.MembersTable,
			Columns: []string{sharedspace.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedspacemember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ssuo.mutation.RootFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sharedspace.RootFileTable,
			Columns: []string{sharedspace.RootFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssuo.mutation.RootFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sharedspace.RootFileTable,
			Columns: []string{sharedspace.RootFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SharedSpace{config: ssuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ssuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ssuo.mutation.done = true
	return _node, nil
}
